services:
  droidbot:
    image: droidbot
    build: ./droidbot-docker
    networks:
      - myNetwork
    volumes:
      - ./output:/output
      - ./apk:/apk
    tty: true
    stdin_open: true

  android-emulator:
    image: us-docker.pkg.dev/android-emulator-268719/images/28-playstore-x64:30.1.2
    env_file:
      - config.env
    devices:
      - /dev/kvm
    ports:
      - "8554:8554/tcp"
      - "5554:5554/tcp"
      - "5555:5555/tcp"
    networks:
      - myNetwork

networks:
  myNetwork:
